---
title: Exploratory Data Analysis
output: html_document
---

This page shows some plots created for exploratory purposes. The plots are interactive so you can hover over to see more specific information. Click [here](https://github.com/BullDF/billboard-songs-analysis-with-spotify/blob/main/EDA/report.pdf) for a written EDA report with analysis.

```{r echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE
)
```

```{r}
library(plotly)
```

```{r}
source("https://raw.githubusercontent.com/BullDF/billboard-songs-analysis-with-spotify/website/data_wrangling.R")
```

```{r}
p <- tracks |>
  count(mode) |>
  ggplot(aes(
    x = mode,
    y = n,
    fill = mode
  )) +
  geom_col() +
  labs(
    x = "Mode",
    y = "Frequency"
  ) +
  ggtitle("Counts of Major vs. Minor Tracks") +
  theme_classic() +
  theme(legend.position = "none")
ggplotly(p, tooltip = "n")
```

```{r}
p <- no_stopwords_top_20 |>
  rename(n = word_freq) |>
  ggplot(aes(
    x = reorder(word, n),
    y = n,
    fill = word
  )) +
  geom_col() +
  labs(
    x = "Word",
    y = "Frequency"
  ) +
  ggtitle("Top 20 Words in Track Names (Stopwords Removed)") +
  theme_classic() +
  theme(legend.position = "none") +
  coord_flip()
ggplotly(p, tooltip = "n")
```

```{r}
p <- tracks_with_artists |>
  group_by(artist_name) |>
  summarize(n = n()) |>
  arrange(desc(n)) |>
  head(20) |>
  ggplot(aes(
    x = reorder(artist_name, n),
    y = n,
    fill = artist_name
  )) +
  geom_col() +
  coord_flip() +
  labs(
    x = "Artist",
    y = "Frequency"
  ) +
  ggtitle("Counts of Artists on Billboard") +
  theme_classic() +
  theme(legend.position = "none")
ggplotly(p, tooltip = "n")
```

```{r}
p <- tracks |>
  ggplot(aes(x = popularity)) +
  geom_histogram(
    binwidth = 2,
    fill = "light blue",
    col = "black"
  ) +
  theme_classic() +
  labs(
    x = "Popularity",
    y = "Frequency"
  ) +
  ggtitle("Distribution of Popularity with Density")
ggplotly(p)
```

```{r}
p <- tracks |>
  ggplot(aes(x = year)) +
  geom_histogram(
    binwidth = 1,
    color = "black",
    fill = "pink"
  ) +
  theme_classic() +
  labs(
    x = "Year",
    y = "Frequency"
  ) +
  ggtitle("Distribution of Tracks over Time")
ggplotly(p)
```

```{r}
p <- tracks |>
  ggplot(aes(x = valence)) +
  geom_histogram(
    binwidth = 2,
    color = "black",
    fill = "yellow"
  ) +
  theme_classic() +
  labs(
    x = "Valence",
    y = "Frequency"
  ) +
  ggtitle("Distribution of Valence")
ggplotly(p)
```

```{r}
p <- tracks |>
  ggplot(aes(x = year, y = popularity)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE, color = "orange") +
  labs(
    x = "Year",
    y = "Popularity"
  ) +
  ggtitle("Popularity vs. Time") +
  theme_classic()
ggplotly(p)
```

```{r}
p <- tracks |>
  ggplot(aes(x = year, y = energy)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE, color = "maroon") +
  labs(
    x = "Year",
    y = "Energy"
  ) +
  ggtitle("Energy vs. Time") +
  theme_classic()
ggplotly(p)
```

```{r}
tracks_with_genres <- read.csv("https://raw.githubusercontent.com/BullDF/billboard-songs-analysis-with-spotify/main/data/ml_analysis/tracks_with_genres.csv")
```

```{r}
p <- tracks_with_genres |>
  count(genre) |>
  ggplot(aes(x = reorder(genre, -n), y = n, fill = genre)) +
  geom_col() +
  theme_classic() +
  theme(legend.position = "none") +
  ggtitle("Count of Music Genres") +
  labs(x = "Genre", y = "Frequency")
ggplotly(p, tooltip = "n")
```
