---
title: Data Wrangling
author: Yuwei (Johnny) Meng -- 1007824810
date: 11 Mar 2024
output: pdf_document
---


Import libraries:

```{r}
library(tidyverse)
library(lubridate)
library(tidytext)
library(wordcloud)
library(tm)
library(gridExtra)
```

```{r}
setwd("/Users/bulldf/University of Toronto/JSC370_project/midterm_project")
```

Read in data:
```{r}
tracks <- read.csv("../data/tracks.csv")
track_artists <- read.csv("../data/track_artists.csv")
artists <- read.csv("../data/artists.csv")

head(tracks)
head(track_artists)
head(artists)
dim(tracks)
dim(track_artists)
dim(artists)
```

# Data Wrangling

```{r}
tracks <- tracks |>
  mutate(
    acousticness = acousticness * 100,
    danceability = danceability * 100,
    energy = energy * 100,
    instrumentalness = instrumentalness * 100,
    liveness = liveness * 100,
    mode = ifelse(mode == "Mode.MAJOR", "major", "minor"),
    speechiness = speechiness * 100,
    valence = valence * 100,
    duration = as.period(seconds_to_period(round(duration_ms / 1000)))
  ) |>
  select(-duration_ms)
head(tracks)
```

# Exploratory Data Analysis

Plot the number of tracks in each key mode:

```{r}
tracks |>
  ggplot(aes(x = mode)) +
  geom_bar()
```

Plot popularity vs. time in year:

```{r}
tracks |>
  ggplot(aes(x = year, y = popularity, color = mode)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE)
```

Plot popularity vs. danceability and valence:

```{r}
tracks |>
  ggplot(aes(y = popularity, x = danceability, color = mode)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE)

tracks |>
  ggplot(aes(y = popularity, x = valence, color = mode)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE)
```

Plot popularity vs. duration:

```{r}
tracks |>
  ggplot(aes(x = period_to_seconds(duration), y = popularity)) +
  geom_point()
```

Look at the name of songs:

```{r}
tracks_tokenized <- tracks |>
  unnest_tokens(word, name)
head(tracks_tokenized)

tracks_tokenized_top_20 <- tracks_tokenized |>
  group_by(word) |>
  summarize(word_freq = n()) |>
  arrange(desc(word_freq)) |>
  head(20)

tracks_tokenized_top_20 |>
  ggplot(aes(x = fct_reorder(word, word_freq), y = word_freq)) +
  geom_col() +
  coord_flip()

wordcloud(tracks_tokenized_top_20$word, tracks_tokenized_top_20$word_freq)

no_stopwords <- tracks_tokenized |>
  filter(!(word %in% stopwords("english"))) |>
  filter(!grepl("[[:digit:]]+", word))

no_stopwords_top_20 <- no_stopwords |>
  group_by(word) |>
  summarize(word_freq = n()) |>
  arrange(desc(word_freq)) |>
  head(20)

no_stopwords_top_20 |>
  ggplot(aes(x = fct_reorder(word, word_freq), y = word_freq)) +
  geom_col() +
  coord_flip()

wordcloud(no_stopwords_top_20$word, no_stopwords_top_20$word_freq)
```

Find the most popular artists:

```{r}
tracks_with_artists <- merge(
  x = track_artists,
  y = artists,
  by.x = "artist_id",
  by.y = "id",
  all.x = TRUE,
  all.y = FALSE
) |>
  rename(artist_name = name)
head(tracks_with_artists)
dim(tracks_with_artists)

tracks_with_artists |>
  group_by(artist_name) |>
  summarize(artist_freq = n()) |>
  arrange(desc(artist_freq)) |>
  head(20) |>
  ggplot(aes(x = fct_reorder(artist_name, artist_freq), y = artist_freq)) +
  geom_col() +
  coord_flip()
```